main:
  runSetup: true
  prefix: "§4§l§oBed§f§l§oWars§a> "
  cannotJoinMessage: "§cV teto fazi se nemuzes pripojit!"
  serverFullMessage: "§cServer je plny"
  joinMessage: "Vitej ve hre, vyber si tym."
  teamSelectorName: "§aVyber tymu"
  teamSelectMenuName: "§2Vyber si tym:"
  teamClickToJoin: "§a§nKlikni pro pripojeni"
  teamIsFull: "§cTeam je plny"
  joinedTeam: "§7Pripojil ses do tymu: "
  unDroppableLore: "§9Undroppable"
  soulBoundLore: "§9Soulbound"
  clickOnBlock: "§cMusis kliknout na blok."
  clickOnBed: "§cMusis kliknout na postel."
  successBedSet: "§aPostel nastavena pro: "
  successSpawnSet: "§aSpawn nastaven pro: "
  successResourceSpawnerAdded: "§aPridan spawner na surovinu "
  successLobbySet: "§aNastaveno herni lobby"
  scoreboardLobbyName: "§4Bed§fWars"
  scoreboardLobbyLines:
    - "Lobby"
    - "Cekani na hrace..."
  scoreboardStartingLines:
    - "Zacatek za: |§a%seconds% §fsekund%suffix%"
  gameStartingIn: "Hra zacina za §9%seconds% §asekund%suffix%!"
  joinBroadcastMessage: "§7Hrac §f%player% §7se §apripojil do hry §7(%online%/%max%)!"
  quitBroadcastMessage: "§7Hrac §f%playerColor%%player% §7se §codpojil ze hry §7(%online%/%max%)!"
  chatFormatLobby: "§7%player% §e§l» §f%message%"
  chatFormatIngameTeam: "%playerColor%§lTEAM§r %playerColor%%player% §7§l» §f%message%"
  chatFormatIngameAll: "§f§lALL§r %playerColor%%player% §7§l» §f%message%"
game:
  minPlayers: 2
  startTime: 30
  startingMessage: "Hra startuje."
  gameStarted: "Hra zacala!"
  notStartingMessage: "Je tu nedostatek hracu, start byl odlozen."
  charHasBed: " §a§l✔"
  charEliminated: " §c§l✘"
  scoreboardFirstLineIngame: "Cas od startu: |§a%time%"
  shopMenuName: "§2Shop"
  shopAlreadyHaveArmor: "§cMuzes si koupit pouze lepsi brneni!"
  shopNotEnoughResources: "§cNemas dostatek itemu ke koupi!"
  cannotDestroyOwnBed: "§cNemuzes znicit svoji postel!"
  bedDestroyed: "§7Hrac %playerColor%%player% §7znicil postel tymu %destroyedTeam%§7."
  destroyedYourBedTitle: "§cZnicena tva postel!"
  destroyedYourBedSubTitle: "§fKdyz umres, uz se nerespawnes."
  playerKilledBy: "§7Hrac %victimColor%%victim% §7byl zabit hracem %killerColor%%killer%."
  playerDied: "§7Hrac %victimColor%%victim% §7zemrel."
  playerEliminated: "§7Hrac %playerColor%%player% §7byl §celiminovan§7."
  arenaRestarting: "§aHra skoncila, arena se restartuje!"
  youHaveWon: "§aGratuluji, VYHRAL jsi hru!"
  arenaRestartingIn: "§aArena se restartuje za %seconds% sekund%suffix%!"
  scoreboardSecondLineRestarting: "Restart za: |§c%seconds% §fsekund%suffix%"
  arenaRestartingNow: "§cArena se restartuje."
shop:
  categoryArmor: "§aBrneni"
  categoryWeapons: "§cZbrane"
  categoryBows: "§6Luky"
  categoryBlocks: "§eBloky"
  categoryTools: "§9Nastroje"
  categorySpecial: "§dSpecialni"
  names:
    armor:
      leather: "§6Kozene brneni"
      iron: "§7Zelezne brneni"
      diamond: "§bDiamantove brneni"
    weapons:
      stick: "§fMrdTycka"
      sword1: "§eMec LVL 1"
      sword2: "§eMec LVL 2"
    bows:
      bow1: "§bLuk LVL 1"
      bow2: "§bLuk LVL 2"
      four_arrows: "§f4× Sip"
    blocks:
      eight_wool: "§f8× Vlna"
      eight_planks: "§68× Drevo"
      four_endstone: "§e4× End Kamen"
      obsidian: "§5Obsidian"
    tools:
      stone_pickaxe: "§7Kamenny krumpac"
      diamond_pickaxe: "§bDiamantovy krumpac"
      shears: "§fNuzky"
    special:
      fireball: "§cFireball"
  prices:
    armor:
      leather: "gold,1"
      iron: "gold,16"
      diamond: "diamond,4"
    weapons:
      stick: "iron,16"
      sword1: "gold,4"
      sword2: "gold,12"
    bows:
      bow1: "gold,8"
      bow2: "gold,24"
      four_arrows: "gold,2"
    blocks:
      eight_wool: "iron,8"
      eight_planks: "iron,24"
      four_endstone: "gold,6"
      obsidian: "emerald,1"
    tools:
      stone_pickaxe: "iron,32"
      diamond_pickaxe: "diamond,4"
      shears: "iron,24"
    special:
      fireball: "iron,32"

arena:
  teams: 4
  playersPerTeam: 4