main:
  prefix: "§4§l§oBed§f§l§oWars§a> "
  cannotJoinMessage: "§cV teto fazi se nemuzes pripojit!"
  joinMessage: "Vitej ve hre, vyber si tym."
  teamSelectorName: "§aVyber tymu"
  unDroppableLore: "§9Undroppable"
game:
  minPlayers: 1
  startTime: 30
  startingMessage: "Hra startuje."
  notStartingMessage: "Je tu nedostatek hracu, start byl odlozen."