name: BedWars
main: com.whitehouse.bedwars.BedWars
version: 1.0
api-version: 1.13
commands:
  bw-setup:
    description: Prepnuti do setup rezimu
    usage: "Pouziti: '/<command>'"
  lobby:
    description: Presunuti na lobby
    usage: "Pouziti: '/<command>'"
  hub:
    description: Presunuti na lobby
    usage: "Pouziti: '/<command>'"